import random

_ADJECTIVES = [
    "BLUE","RED","GOLD","NEON","CALM","BOLD","SOFT","WILD","DARK","STAR",
    "IRON","SNOW","JADE","ROSE","TEAL","AQUA","LIME","RUBY","ONYX","MINT",
    "SAGE","DAWN","DUSK","HAZE","MIST","MOON","NOVA","OPAL","PINK","PLUM",
    "CYAN","GRAY","WARM","COOL","FAST","VAST","PURE","KEEN","ARCH","APEX",
    "BARE","BOLD","BRAVE","BRIGHT","BRISK","BRINE","BROW","BUFF","CALM","CLEAR",
    "CRISP","DEEP","DENSE","DEFT","DUAL","DUSK","EPIC","EVEN","FAIR","FINE",
    "FIRM","FLAT","FLEET","FLOW","FOAM","FOND","FORT","FREE","FULL","GLOW",
    "GRAND","GREAT","HALE","HARD","HAZY","HIGH","HUGE","JUST","KEEN","KIND",
    "LACY","LEAN","LUSH","LYRIC","MAUVE","MILD","MUTE","NEAT","NICE","NIMBLE",
    "NOBLE","NORTH","OCRE","OPEN","PEAR","PINE","POLAR","PRIME","PROUD","QUIET",
]

_NOUNS = [
    "SHARK","TIGER","EAGLE","LOTUS","RIVER","STONE","FLAME","OCEAN","CLOUD","STORM",
    "COMET","WOLF","BEAR","HAWK","CRANE","WHALE","ZEBRA","PANDA","KITE","PEARL",
    "ORBIT","PRISM","QUARTZ","RAVEN","SOLAR","TOWER","ULTRA","VIPER","XENON","YACHT",
    "ZENITH","ALPHA","BLADE","CEDAR","DELTA","EMBER","FROST","GROVE","HAVEN","ISLE",
    "JAGGED","KARMA","LANCE","MAPLE","NEXUS","OASIS","PHASE","RIDGE","SIGMA","TERRA",
    "UNITE","VALOR","WALTZ","XYLO","YIELD","ZONAL","ARROW","BASALT","CREST","DRIFT",
    "EPOCH","FJORD","GLYPH","HARBOR","INLET","JEWEL","KNOLL","LAGOON","MANOR","NADIR",
    "OBSIDIAN","PEAK","QUILL","REALM","SPIRAL","TROVE","UMBRA","VAULT","WHIRL","EXPANSE",
    "YONDER","ZONE","ACORN","BROOK","CANYON","DELL","ESTUARY","FEN","GLADE","HEATH",
    "IRIS","JASPER","KELP","LEDGE","MESA","NOOK","PINNACLE","RAVINE","SEDGE","TUNDRA",
]


def generate_code() -> str:
    adj  = random.choice(_ADJECTIVES)
    noun = random.choice(_NOUNS)
    return f"{adj}-{noun}"
